In [1]:
import pandas as pd 
import numpy as np
df=pd.read_csv(r"C:\Users\hp\OneDrive\Documents\projects\Healthcare Operations & Patient Analytics\Data\HospitalOPD-noname.csv")
df

,record_no,patient_id,Unnamed: 2,appointment_id,appointment_start_datetime,prescription_doctor_id,prescription_doctor_name,prescription_order_id,prescription_start_datetime,prescription_end_datetime,...,imaging_result_id,imaging_name,imaging_start_datetime,imaging_end_datetime,pharmacy_sale_line_id,medicine_name,pharmacy_start_datetime,pharmacy_end_datetime,flow_code,flow_name
0,1,10,NaN,445911,3/30/2026 5:36,225,Admin,106357,3/30/2026 5:38,3/30/2026 6:48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
1,2,57,NaN,335085,10/14/2025 5:23,193,Dr. Abrar Ahmed Bhatti,43515,10/14/2025 5:39,10/14/2025 5:53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
2,3,57,NaN,335085,10/14/2025 5:23,193,Dr. Abrar Ahmed Bhatti,43541,10/14/2025 6:11,10/14/2025 6:24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
3,4,60,NaN,322358,9/25/2025 13:36,195,Dr. Anique Ahmed,34654,9/25/2025 13:50,9/25/2025 13:51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
4,5,72,NaN,337714,10/17/2025 6:40,202,Dr. Mehreen Batool Bokhari,45263,10/17/2025 6:49,10/17/2025 6:49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62417,62418,308354,NaN,452026,04-07-2026 07:10,158,Dr. Muhammad Atif Mumtaz,109484,04-07-2026 07:15,04-07-2026 07:15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
62418,62419,308357,NaN,452035,04-07-2026 07:20,202,Dr. Mehreen Batool Bokhari,109500,04-07-2026 07:28,04-07-2026 07:31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
62419,62420,308360,NaN,452062,04-07-2026 07:34,193,Dr. Abrar Ahmed Bhatti,109508,04-07-2026 07:36,04-07-2026 07:50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
62420,62421,308363,NaN,452072,04-07-2026 07:42,179,Dr. Ehsan-Ul-Haq,109533,04-07-2026 08:02,04-07-2026 08:02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription
62421,62422,308365,NaN,452080,04-07-2026 07:47,169,Dr. Ammad Iftikhar,109522,04-07-2026 07:52,04-07-2026 07:53,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,Appointment → Prescription

In [2]:
df.shape

(62422, 25)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62422 entries, 0 to 62421
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   record_no                    62422 non-null  int64
 1   patient_id                   62422 non-null  int64
 2   Unnamed: 2                   0 non-null      float64
 3   appointment_id               62422 non-null  int64
 4   appointment_start_datetime   62422 non-null  object
 5   prescription_doctor_id       62422 non-null  int64
 6   prescription_doctor_name     62422 non-null  object
 7   prescription_order_id        62422 non-null  int64
 8   prescription_start_datetime  62410 non-null  object
 9   prescription_end_datetime    62421 non-null  object
 10  lab_id                       18029 non-null  float64
 11  lab_name                     18029 non-null  object
 12  lab_start_datetime           18029 non-null  object
 13  lab_end_datetime             18029 non-null  object
 14  imaging_request_id           5523 non-null   float64
 15  imaging_result_id            5523 non-null   float64
 16  imaging_name                 5523 non-null   object
 17  imaging_start_datetime       5523 non-null   object
 18  imaging_end_datetime         5513 non-null   object
 19  pharmacy_sale_line_id        302 non-null    float64
 20  medicine_name                302 non-null    object
 21  pharmacy_start_datetime      302 non-null    object
 22  pharmacy_end_datetime        302 non-null    object
 23  flow_code                    62422 non-null  int64
 24  flow_name                    62422 non-null  object
dtypes: float64(5), int64(6), object(14)
memory usage: 11.9+ MB

In [4]:
df.isna().sum()

record_no                          0
patient_id                         0
Unnamed: 2                     62422
appointment_id                     0
appointment_start_datetime         0
prescription_doctor_id             0
prescription_doctor_name           0
prescription_order_id              0
prescription_start_datetime       12
prescription_end_datetime          1
lab_id                         44393
lab_name                       44393
lab_start_datetime             44393
lab_end_datetime               44393
imaging_request_id             56899
imaging_result_id              56899
imaging_name                   56899
imaging_start_datetime         56899
imaging_end_datetime           56909
pharmacy_sale_line_id          62120
medicine_name                  62120
pharmacy_start_datetime        62120
pharmacy_end_datetime          62120
flow_code                          0
flow_name                          0
dtype: int64

In [5]:
df.nunique()

record_no                      62422
patient_id                     39442
Unnamed: 2                         0
appointment_id                 49912
appointment_start_datetime     43305
prescription_doctor_id            98
prescription_doctor_name          98
prescription_order_id          50568
prescription_start_datetime    43384
prescription_end_datetime      43261
lab_id                         17083
lab_name                         119
lab_start_datetime              6414
lab_end_datetime               11719
imaging_request_id              5360
imaging_result_id               5360
imaging_name                      38
imaging_start_datetime          5270
imaging_end_datetime            5271
pharmacy_sale_line_id            262
medicine_name                    154
pharmacy_start_datetime          112
pharmacy_end_datetime            118
flow_code                          7
flow_name                          7
dtype: int64

In [6]:
df["Unnamed: 2"].isna().sum()/len(df)*100

np.float64(100.0)

In [7]:
c=df.columns
for a in c:
    if ((df[a].isna().sum()/len(df)*100)>70):
        df.drop(a,inplace=True,axis=1)

In [8]:

df.shape

(62422, 11)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62422 entries, 0 to 62421
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   record_no                    62422 non-null  int64
 1   patient_id                   62422 non-null  int64
 2   appointment_id               62422 non-null  int64
 3   appointment_start_datetime   62422 non-null  object
 4   prescription_doctor_id       62422 non-null  int64
 5   prescription_doctor_name     62422 non-null  object
 6   prescription_order_id        62422 non-null  int64
 7   prescription_start_datetime  62410 non-null  object
 8   prescription_end_datetime    62421 non-null  object
 9   flow_code                    62422 non-null  int64
 10  flow_name                    62422 non-null  object
dtypes: int64(6), object(5)
memory usage: 5.2+ MB

In [10]:
df[df.isnull().any(axis=1)]

,record_no,patient_id,appointment_id,appointment_start_datetime,prescription_doctor_id,prescription_doctor_name,prescription_order_id,prescription_start_datetime,prescription_end_datetime,flow_code,flow_name
202,203,1221,303351,09-01-2025 03:49,183,Dr. Asia Ashraf,22961,NaN,09-01-2025 07:13,1,Appointment → Prescription
26488,26489,218455,310191,09-10-2025 11:00,542,Dr Sadaf Asma,27227,NaN,09-10-2025 11:31,1,Appointment → Prescription
28525,28526,228782,274446,7/21/2025 4:58,502,Dr. Ifra Khwaja (MO),16249,7/21/2025 5:05,NaN,1,Appointment → Prescription
30753,30754,238264,306098,09-04-2025 09:20,183,Dr. Asia Ashraf,24640,NaN,09-04-2025 13:46,1,Appointment → Prescription
32998,32999,244205,307386,09-06-2025 05:13,185,Dr. Rizwana Kausar,25246,NaN,09-06-2025 05:59,1,Appointment → Prescription
33640,33641,245277,307778,09-07-2025 07:00,543,Dr. Muneeba Manzoor,25568,NaN,09-07-2025 07:05,1,Appointment → Prescription
33694,33695,245349,310751,09-11-2025 06:03,179,Dr. Ehsan-Ul-Haq,27550,NaN,09-11-2025 06:20,1,Appointment → Prescription
33730,33731,245400,308012,09-08-2025 04:27,193,Dr. Abrar Ahmed Bhatti,25767,NaN,09-08-2025 07:29,1,Appointment → Prescription
33811,33812,245506,308284,09-08-2025 07:18,193,Dr. Abrar Ahmed Bhatti,25943,NaN,09-08-2025 08:03,1,Appointment → Prescription
34880,34881,247184,311847,09-12-2025 12:37,348,Dr. Sarah Faiz,28273,NaN,09-12-2025 13:19,1,Appointment → Prescription
35181,35182,247779,313036,9/14/2025 11:35,251,Dr. Izzah Sikandar,28841,NaN,9/14/2025 11:52,1,Appointment → Prescription
35412,35413,248184,313936,9/15/2025 13:43,348,Dr. Sarah Faiz,29439,NaN,9/15/2025 14:49,1,Appointment → Prescription
35440,35441,248210,314006,9/15/2025 14:12,539,Dr. Basit Bashir,29408,NaN,9/15/2025 14:23,1,Appointment → Prescription

In [11]:
df=df.dropna(subset=["prescription_start_datetime","prescription_end_datetime"])
df.shape

(62409, 11)

In [12]:
df[df.duplicated()]

Empty DataFrame
Columns: [record_no, patient_id, appointment_id, appointment_start_datetime, prescription_doctor_id, prescription_doctor_name, prescription_order_id, prescription_start_datetime, prescription_end_datetime, flow_code, flow_name]
Index: []

In [ ]:

df["prescription_start_datetime"] = pd.to_datetime(df["prescription_start_datetime"], format="mixed")
df["prescription_end_datetime"] = pd.to_datetime(df["prescription_end_datetime"], format="mixed")
df["appointment_start_datetime"] = pd.to_datetime(df["appointment_start_datetime"], format="mixed")

In [ ]:
df['prescription_duration'] = df['prescription_end_datetime'] - df['prescription_start_datetime']
df["prescription_duration"].describe()

In [ ]:
cols_to_check = [
    "patient_id", "appointment_id", "appointment_start_datetime", 
    "prescription_doctor_id", "prescription_doctor_name", "prescription_order_id", 
    "prescription_start_datetime", "prescription_end_datetime", 
    "flow_code", "flow_name", "prescription_duration"
]
df[df.duplicated(subset=cols_to_check,keep=False)].shape

In [ ]:
df = df.drop_duplicates(subset=cols_to_check, keep="first")

In [ ]:
df[df.duplicated(subset=cols_to_check,keep=False)].shape

In [ ]:
df[df["prescription_duration"] >"1 days 00:00:00"].sort_values(by="prescription_duration")

In [ ]:
df.loc[df["record_no"] == 6101, "prescription_end_datetime"] = "2025-10-17 06:55:00"
df.loc[df["record_no"] == 16296, "prescription_end_datetime"] = "2026-02-25 06:35:00"
df.loc[df["record_no"] == 54223, "prescription_end_datetime"] = "2026-01-20 06:47:00"
df.loc[df["record_no"] == 23341, "prescription_end_datetime"] = "2025-04-9 05:52:00"
df.loc[df["record_no"] == 23342, "prescription_end_datetime"] = "2025-04-9 05:52:00"
df.loc[df["record_no"] == 60219, "prescription_end_datetime"] = "2026-03-9 07:35:00"
df.loc[df["record_no"] == 17468, "prescription_end_datetime"] = "2025-04-16 13:11:00"
df.loc[df["record_no"] == 1342, "prescription_end_datetime"] = "2026-01-03 18:27:00"
df.loc[df["record_no"] == 51617, "prescription_end_datetime"] = "2025-12-29 20:03:00"
df.loc[df["record_no"] == 12288, "prescription_end_datetime"] = "2025-03-26 04:48:00"
df.loc[df["record_no"] == 2477, "prescription_end_datetime"] = "2025-09-25 05:42:00"
df.loc[df["record_no"] == 1052, "prescription_end_datetime"] = "2025-03-24 05:57:00"
df.loc[df["record_no"] == 36442, "prescription_end_datetime"] = "2025-09-20 07:45:00"
df.loc[df["record_no"] == 37219, "prescription_end_datetime"] = "2025-09-24 04:54:00"
df.loc[df["record_no"] == 36394, "prescription_end_datetime"] = "2025-09-19 15:01:00"
df.loc[df["record_no"] == 17522, "prescription_end_datetime"] = "2025-10-24 05:16:00"
df.loc[df["record_no"] == 44170, "prescription_end_datetime"] = "2026-03-25 06:36:00"
df.loc[df["record_no"] == 44169, "prescription_end_datetime"] = "2026-03-25 06:36:00"
df.loc[df["record_no"] == 43150, "prescription_end_datetime"] = "2025-10-27 16:56:00"
df.loc[df["record_no"] == 41569, "prescription_end_datetime"] = "2025-10-16 08:16:00"
df.loc[df["record_no"] == 2826, "prescription_end_datetime"] = "2025-09-12 08:08:00"
df.loc[df["record_no"] == 23803, "prescription_end_datetime"] = "2025-05-24 06:32:00"
df.loc[df["record_no"] == 25391, "prescription_end_datetime"] = "2025-05-22 06:56:00"
df.loc[df["record_no"] == 25392, "prescription_end_datetime"] = "2025-05-22 06:56:00"
df.loc[df["record_no"] == 22398, "prescription_end_datetime"] = "2025-05-24 14:42:00"
df.loc[df["record_no"] == 23366, "prescription_end_datetime"] = "2026-03-2 06:39:00"
df.loc[df["record_no"] == 57436, "prescription_end_datetime"] = "2026-02-13 04:33:00"
df.loc[df["record_no"] == 40, "prescription_end_datetime"] = "2025-08-9 12:02:00"
df.loc[df["record_no"] == 22119, "prescription_end_datetime"] = "2025-02-25 03:16:00"
df.loc[df["record_no"] == 17824, "prescription_end_datetime"] = "2025-06-2 05:46:00"
df.loc[df["record_no"] == 26038,"prescription_end_datetime"] = "2025-08-13 06:57:00"
df.loc[df["record_no"] == 28837,"prescription_end_datetime"]="2025-07-23 16:43:00"

In [ ]:
df[df['appointment_start_datetime'] > df['prescription_start_datetime']]

In [ ]:
mask = df['appointment_start_datetime'] > df['prescription_start_datetime']
df.loc[mask, ['appointment_start_datetime','prescription_start_datetime']] = df.loc[mask, 
    ['prescription_start_datetime','appointment_start_datetime']].to_numpy()
df[df['appointment_start_datetime'] > df['prescription_start_datetime']].value_counts()

In [ ]:
df[df['prescription_end_datetime'] < df['prescription_start_datetime']]

In [ ]:
mask=df['prescription_end_datetime'] < df['prescription_start_datetime']
df.loc[mask, ['prescription_start_datetime','prescription_end_datetime']] = df.loc[mask, 
    ['prescription_end_datetime','prescription_start_datetime']].to_numpy()

In [ ]:
df[df['prescription_end_datetime'] < df['prescription_start_datetime']].value_counts()

In [ ]:
df['prescription_duration'] = df['prescription_end_datetime'] - df['prescription_start_datetime']
df["prescription_duration"].describe()

In [ ]:
df[df["prescription_duration"] >"0 days 09:59:00"]

In [ ]:
len(df[df["prescription_duration"]=="0 days 00:00:00"])/len(df)*100

In [ ]:
Q1 = df['prescription_duration'].quantile(0.25)
Q3 = df['prescription_duration'].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df['prescription_duration'] < lower_limit) |
    (df['prescription_duration'] > upper_limit)
]

outliers.shape

In [ ]:
#Total records
df.shape

In [ ]:
#Unique patients/appointments/prescriptions/doctors
print("Unique patients:", df["patient_id"].nunique())
print("Unique appointments:", df["appointment_id"].nunique())
print("Unique prescriptions:", df["prescription_order_id"].nunique())
print("Unique doctors:", df["prescription_doctor_id"].nunique())

In [ ]:
#Data period
print("Start date:", df["appointment_start_datetime"].min())
print("End date:", df["appointment_start_datetime"].max())

In [ ]:
#Different pathways
df["flow_name"].value_counts()

In [ ]:
#How many patients per pathway
df.groupby("flow_name")["patient_id"].nunique()

In [ ]:
# % stop after prescription
lab_flows=["Appointment → Prescription → Lab","Appointment → Prescription → Imaging","Appointment → Prescription → Pharmacy","Appointment → Prescription → Lab + Imaging","Appointment → Prescription → Lab + Pharmacy","Appointment → Prescription → Imaging + Pharmacy"]
condition=(df["flow_name"]=="Appointment → Prescription") & (~df["flow_name"].isin(lab_flows))
df[condition]["patient_id"].nunique()/df["patient_id"].nunique()*100

In [ ]:
# % continue to Lab/Imaging/Pharmacy
lab_flows=["Appointment → Prescription → Lab","Appointment → Prescription → Imaging","Appointment → Prescription → Pharmacy","Appointment → Prescription → Lab + Imaging","Appointment → Prescription → Lab + Pharmacy","Appointment → Prescription → Imaging + Pharmacy"]
df[df["flow_name"].isin(lab_flows)]["patient_id"].nunique()/df["patient_id"].nunique()*100

In [ ]:
# % multiple downstream services
lab_flows=["Appointment → Prescription → Lab + Imaging","Appointment → Prescription → Lab + Pharmacy","Appointment → Prescription → Imaging + Pharmacy"]
df[df["flow_name"].isin(lab_flows)]["patient_id"].nunique()/df["patient_id"].nunique()*100

In [ ]:
#Lab frequency
lab_flows=["Appointment → Prescription → Lab","Appointment → Prescription → Lab + Imaging","Appointment → Prescription → Lab + Pharmacy"]
df[df["flow_name"].isin(lab_flows)].groupby(df["prescription_end_datetime"].dt.month)["flow_name"].count()

In [ ]:
# Imaging frequency
lab_flows=["Appointment → Prescription → Imaging","Appointment → Prescription → Lab + Imaging","Appointment → Prescription → Imaging + Pharmacy"]
df[df["flow_name"].isin(lab_flows)].groupby(df["prescription_end_datetime"].dt.month)["flow_name"].count()

In [ ]:
#Pharmacy frequency
lab_flows=["Appointment → Prescription → Pharmacy","Appointment → Prescription → Lab + Pharmacy","Appointment → Prescription → Imaging + Pharmacy"]
df[df["flow_name"].isin(lab_flows)].groupby(df["prescription_end_datetime"].dt.month)["flow_name"].count()

In [ ]:
#Service combinations
pattern = "Appointment → Prescription → Lab \+ Imaging|Appointment → Prescription → Lab \+ Pharmacy|Appointment → Prescription → Imaging \+ Pharmacy"
df[df["flow_name"].str.contains(pattern,na=False)]["flow_name"].value_counts()

In [ ]:
# Service utilization over time
monthly_service = (
    df.assign(
        month=df["appointment_start_datetime"].dt.to_period("M"),
        has_lab=df["flow_name"].str.contains("Lab", na=False),
        has_imaging=df["flow_name"].str.contains("Imaging", na=False),
        has_pharmacy=df["flow_name"].str.contains("Pharmacy", na=False)
    )
    .groupby("month")[["has_lab", "has_imaging", "has_pharmacy"]]
    .mean()
    .mul(100)
)
monthly_service

In [ ]:
#Prescriptions per doctor
df.groupby("prescription_doctor_name")["prescription_order_id"].nunique().sort_values(ascending=False)

In [ ]:
# Pathway distribution by doctor
pd.crosstab(
    df["prescription_doctor_name"],
    df["flow_name"],
    normalize="index"
) * 100

In [ ]:

# Proportion requiring Lab
df["has_Lab"] = df["flow_name"].str.contains("Lab", na=False)
df.groupby("prescription_doctor_name")["has_Lab"].mean().mul(100).sort_values(ascending=False)

In [ ]:
# Proportion requiring Imaging
df["has_Imaging"] = df["flow_name"].str.contains("Imaging", na=False)
df.groupby("prescription_doctor_name")["has_Imaging"].mean().mul(100).sort_values(ascending=False)

In [ ]:
#Proportion requiring Pharmacy
df["has_Pharmacy"] = df["flow_name"].str.contains("Pharmacy", na=False)
df.groupby("prescription_doctor_name")["has_Pharmacy"].mean().mul(100).sort_values(ascending=False)

In [ ]:
# Proportion requiring Multiple Service
df["multi_service"] = (df[["has_Lab","has_Imaging","has_Pharmacy"]].sum(axis=1)>=2)
df.groupby("prescription_doctor_name")["multi_service"].mean().mul(100).sort_values(ascending=False)

In [ ]:
# Average Duration
df["prescription_duration"].mean()

In [ ]:
#Median Duration
df["prescription_duration"].median()

In [ ]:
# distribution of prescription duration
df["prescription_duration"].describe()

In [ ]:
# Duration by doctor
df.groupby("prescription_doctor_name")["prescription_duration"].mean().sort_values(ascending=False)

In [ ]:
#Unusually long durations
df[df["prescription_duration"] > pd.Timedelta(hours=10)]

In [ ]:
#Monthly appointment volume
df.groupby(df["appointment_start_datetime"].dt.to_period("M"))["appointment_id"].nunique()

In [ ]:
# Monthly Prescription volume
df.groupby(df['prescription_start_datetime'].dt.to_period("M"))['prescription_order_id'].nunique()

In [ ]:
# Lab utilization over time
df.groupby(df["appointment_start_datetime"].dt.to_period("M"))["has_Lab"].mean().mul(100)

In [ ]:
# Imaging utilization over time
df.groupby(df["appointment_start_datetime"].dt.to_period("M"))["has_Imaging"].mean().mul(100)

In [ ]:
# Multi-service journeys over time
target_flows = ["Appointment → Prescription → Lab + Imaging","Appointment → Prescription → Lab + Pharmacy","Appointment → Prescription → Imaging + Pharmacy"]
df[df["flow_name"].isin(target_flows)].groupby(df['prescription_start_datetime'].dt.to_period("M"))['prescription_start_datetime'].count()

In [ ]:
# Prescription duration over time
df.groupby(df['prescription_start_datetime'].dt.to_period("M"))['prescription_duration'].mean()

In [ ]:
# Extract Duration into seconds
df['prescription_duration'] = df['prescription_duration'].dt.total_seconds()

In [ ]:
df

In [ ]:
df=df[["record_no","patient_id","appointment_id","appointment_start_datetime","prescription_doctor_id","prescription_doctor_name","prescription_order_id","prescription_start_datetime","prescription_end_datetime","flow_code","flow_name","prescription_duration"]]

In [ ]:
df.info()

In [ ]:
df.to_csv(r"C:\Users\hp\OneDrive\Documents\projects\Healthcare Operations & Patient Analytics\Data\cleaned_HospitalOPD-noname.csv",index=False)